version: "2"

services:
  db:
    image: deadrobots/pixi:datastore
    container_name: pixidb
    ports:
      - "27017:27017"
      - "28017:28017"
    expose:
      - "27017"
      - "28017"

  app:
    image: 42crunch/pixi:42c
    container_name: pixiapp
    ports:
      - "8000:8000"
      - "8090:8090"
    environment: 
      - MONGO_URL=mongodb://pixidb:27017/Pixidb